name: {{ name }}
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  flutter_flavorizr:
  cupertino_icons: ^1.0.6
  go_router: ^13.2.4
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  logger: ^2.2.0
  stack_trace: ^1.11.1
  connectivity_plus: ^6.0.2
  version: ^3.0.2
  freezed_annotation: ^2.4.1
  package_info_plus: ^7.0.0
  device_info_plus: ^10.1.0
  firebase_analytics: ^10.10.2
  firebase_core: ^2.30.0
  firebase_messaging: ^14.8.2
  webview_flutter: ^4.7.0
  intl: ^0.18.1

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  go_router_builder: ^2.5.1
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  riverpod_lint: ^2.3.10
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
